package decompiler.tags.doabc.instruction
{
	import decompiler.utils.SWFUtil;
	import decompiler.utils.SWFXML;
	
	import flash.utils.ByteArray;

	/**
	 * Format
		construct
		arg_count
	 * arg_count is a u30 that is the number of arguments present on the stack. 
	 * object is the function that is being constructed. 
	 * This will invoke the [[Construct]] property on object with the given arguments. 
	 * The new instance generated by invoking [[Construct]] will be pushed onto the stack.
	 * @author ukyohpq
	 * 
	 */
	public class Construct extends AbstractInstruction
	{
		private var _arg_count:uint;

		public function get arg_count():uint
		{
			return _arg_count;
		}

		public function set arg_count(value:uint):void
		{
			_arg_count = value;
		}

		public function Construct()
		{
			super();
		}
		
		override public function getForm():int
		{
			return 66;
		}
		
		override public function getName():String
		{
			return "construct";
		}
		
		override public function decodeFromBytes(byte:ByteArray):void
		{
			_arg_count = SWFUtil.readU30(byte);
		}
		
		override protected function encodeBody(byte:ByteArray):void
		{
			SWFUtil.writeU30(byte, _arg_count);
		}
		
//		override public function toString():String
//		{
//			return "[ construct arg_count:" + arg_count + " ]";
//		}
		
		override protected function stringBody():String
		{
			return "arg_count:" + _arg_count;
		}
		
		override public function getParams():Vector.<uint>
		{
			return new <uint>[_arg_count];
		}
		
		override protected function paramsToXML(xml:SWFXML):void
		{
			xml.appendChild("<arg_count>" + _arg_count + "</arg_count>");
		}
		
		
	}
}